#!/bin/bash
# assocplot 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

main() {

    echo "Value of datafile: '$datafile'"
    echo "Value of ldfile: '$ldfile'"
    echo "Value of label: '$label'"
    echo "Value of output_type: '$output_type'"
    echo "Value of output_args: '$output_args'"
    echo "Value of traitname: '$traitname'"
    echo "Value of groupname: '$groupname'"
    echo "Value of ld_filetype: '$ld_filetype'"
    echo "Value of snp_col: '$snp_col'"
    echo "Value of gene_col: '$gene_col'"
    echo "Value of chr_col: '$chr_col'"
    echo "Value of pos_col: '$pos_col'"
    echo "Value of p_col: '$p_col'"
    echo "Value of freq_col: '$freq_col'"
    echo "Value of hetdf_col: '$hetdf_col'"
    echo "Value of index_snp: '$index_snp'"
    echo "Value of index_gene: '$index_gene'"
    echo "Value of index_region: '$index_region'"
    echo "Value of region_width: '$region_width'"
    echo "Value of ancestry: '$ancestry'"
    echo "Value of chromosome: '$chr'"


    dx download "$datafile" -o datafile
    dx download "$datafile"
    dx download "$ldfile" -o ldfile

    # datafile_name=$( dx describe "$datafile" | awk '{ if ($1=="Name") print $2 }' ) #old way -- when filenames were very long, dx describe would truncate them
    datafile_name=$( dx describe "$datafile" --name )

    wait

    ls -sh
    echo "Running R script..."

    # Rscript /make.assocplot.R $datafile_name ldfile $ld_filetype $snp_col $gene_col $chr_col $pos_col $p_col $freq_col $hetdf_col $index_snp $region_width $ancestry $chr $index_gene $index_region $traitname $groupname
    Rscript /make.assocplot.R "$datafile_name;ldfile;$ld_filetype;$snp_col;$gene_col;$chr_col;$pos_col;$p_col;$freq_col;$hetdf_col;$index_snp;$region_width;$ancestry;$chr;$index_gene;$index_region;$traitname;$groupname;$output_type;$output_args"

    ls -sh

    mv assoc.$output_type ${label}_assoc.$output_type
    assoc_plot=$(dx upload ${label}_assoc.$output_type --brief)


    dx-jobutil-add-output assoc_plot "$assoc_plot" --class=file

}
